### ISSUE TITLE
Abstraksjon og kode oppryding, implementere actions

### ISSUE THREAD

**Issue by Katrix** [inf112-v21/IsolasjonsTeamet#16]
Person nr 1 fokuserer på abstraksjon og kode oppryding. Andre fokuserer på å implementere `Action#perform`.
Viktig at det går an å bruke disse metodene uten noe grafisk eller lignende. Skal virke helt fint på server side uten en grafisk klient.

Tenker vi bør ende opp med noe slikt som dette
```java
interface Board {
    
    List<Player> getPlayers();
    
    @Nullable Player getPlayerAt(Vec2i pos);
    
    List<TileType> getTilesAt(Vec2i pos);
}

interface Player {

    Vec2i getPos();
    
    void move(Vec2i amount);
}

interface Action {

    void perform(Board board, Player player);
}
```

**Comment by kaspermelheim** [comment]
On it

**Comment by Katrix** [comment]
Closed by #28
